Adapted for cloning LibreELEC

diff --git a/rpi-clone b/rpi-clone
--- a/rpi-clone
+++ b/rpi-clone
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+# Adpated for cloning LibreELEC
+# from https://github.com/billw2/rpi-clone/commit/f961aee3f9816d345c2df335aa96b3907ee68b09 
+
 VERSION=1.5
 # Version 1.5	2016/09/09
 #	* Remove any leading /dev/ from dest disk.
@@ -24,11 +27,11 @@ PGM=`basename $0`
 
 RSYNC_OPTIONS="--force -rltWDEgopt"
 
-# List of extra dirs to create under /mnt.
+# List of extra dirs to create under /storage.
 OPTIONAL_MNT_DIRS="clone mnt sda sdb rpi0 rpi1"
 
 # Where to mount the disk filesystems to be rsynced.
-CLONE=/mnt/clone
+CLONE=/storage/clone
 
 CLONE_LOG=/var/log/$PGM.log
 
@@ -52,7 +55,7 @@ then
 	exit 0
 fi
 
-if test -e /sbin/fsck.vfat
+if test -e /usr/sbin/fsck.vfat
 then
 	HAVE_FSCK_VFAT="yes"
 else
@@ -140,7 +143,7 @@ then
 fi
 
 # Remove leading /dev/
-DIR=`expr substr $DST_DISK 1 5`
+DIR=${DST_DISK:0:5}
 if [ "$DIR" == "/dev/" ]
 then
 	DST_DISK=${DST_DISK#/dev/}
@@ -156,7 +159,7 @@ then
 fi
 
 CHK_DISK=`cat /proc/partitions | grep -m 1 $DST_DISK`
-D=${CHK_DISK: -1}
+D=${CHK_DISK:-1}
 if [ "$D" -eq "$D" ] 2>/dev/null
 then
 	echo "  The target disk you entered, $DST_DISK, ends with a digit and this"
@@ -316,7 +319,7 @@ then
 		PART2_START=$(parted /dev/mmcblk0 -ms unit MB p | grep "^2" \
 				| cut -f 2 -d: | sed s/MB// | tr "," "." | cut -f 1 -d.)
 		# and add some slop
-		DD_COUNT=`expr $PART2_START + 8`
+		DD_COUNT=$(($PART2_START + 8))
 
 		echo ""
 		echo "Imaging the partition structure, copying $DD_COUNT megabytes..."
@@ -335,8 +338,8 @@ then
 		# maybe the wrong size for the destination SD card.  So fdisk it to
 		# make it fill the rest of the disk and mkfs it to clean it out.
 		#
-		echo "Sizing partition 2 (root partition) to use all SD card space..."
-		expand_rootfs
+		#echo "Sizing partition 2 (root partition) to use all SD card space..."
+		#expand_rootfs
 		mkfs.ext4 -F $DST_ROOT_PARTITION
 
 		echo ""
@@ -406,18 +409,18 @@ then
 	exit 0
 fi
 
-if [ ! -d $CLONE/boot ]
-then
-	mkdir $CLONE/boot
-fi
+#if [ ! -d $CLONE/boot ]
+#then
+#	mkdir $CLONE/boot
+#fi
 
-echo "=> Mounting $DST_BOOT_PARTITION on $CLONE/boot"
-if ! mount $DST_BOOT_PARTITION $CLONE/boot
-then
-	umount $CLONE
-	echo -e "Mount failure of $DST_BOOT_PARTITION, aborting!\n"
-	exit 0
-fi
+#echo "=> Mounting $DST_BOOT_PARTITION on $CLONE/boot"
+#if ! mount $DST_BOOT_PARTITION $CLONE/boot
+#then
+#	umount $CLONE
+#	echo -e "Mount failure of $DST_BOOT_PARTITION, aborting!\n"
+#	exit 0
+#fi
 
 echo "==============================="
 
@@ -452,8 +455,9 @@ rsync $RSYNC_OPTIONS --delete \
 		--exclude '/run' \
 		--exclude '/sys' \
 		--exclude '/tmp' \
+		--exclude 'clone' \
 		--exclude 'lost\+found' \
-	// \
+	/storage/ \
 	$CLONE
 
 
@@ -461,38 +465,38 @@ rsync $RSYNC_OPTIONS --delete \
 # Fixup some stuff
 #
 
-for i in dev media mnt proc run sys
-do
-	if [ ! -d $CLONE/$i ]
-	then
-		mkdir $CLONE/$i
-	fi
-done
+#for i in dev media mnt proc run sys
+#do
+#	if [ ! -d $CLONE/$i ]
+#	then
+#		mkdir $CLONE/$i
+#	fi
+#done
 
-if [ ! -d $CLONE/tmp ]
-then
-	mkdir $CLONE/tmp
-	chmod a+w $CLONE/tmp
-fi
+#if [ ! -d $CLONE/tmp ]
+#then
+#	mkdir $CLONE/tmp
+#	chmod a+w $CLONE/tmp
+#fi
 
 # Some extra optional dirs I create under /mnt
-for i in $OPTIONAL_MNT_DIRS
-do
-	if [ ! -d $CLONE/mnt/$i ]
-	then
-		mkdir $CLONE/mnt/$i
-	fi
-done
+#for i in $OPTIONAL_MNT_DIRS
+#do
+#	if [ ! -d $CLONE/mnt/$i ]
+#	then
+#		mkdir $CLONE/mnt/$i
+#	fi
+#done
 
-rm -f $CLONE/etc/udev/rules.d/70-persistent-net.rules
+#rm -f $CLONE/etc/udev/rules.d/70-persistent-net.rules
 
 
 DATE=`date '+%F %H:%M'`
 
 echo "$DATE  $HOSTNAME $PGM : clone to $DST_DISK ($DST_ROOT_VOL_NAME)" \
 		>> $CLONE_LOG
-echo "$DATE  $HOSTNAME $PGM : clone to $DST_DISK ($DST_ROOT_VOL_NAME)" \
-		>> $CLONE/$CLONE_LOG
+#echo "$DATE  $HOSTNAME $PGM : clone to $DST_DISK ($DST_ROOT_VOL_NAME)" \
+#		>> $CLONE/$CLONE_LOG
 
 
 STOP_TIME=`date '+%H:%M:%S'`
@@ -507,14 +511,14 @@ echo ""
 # Eg. modify $CLONE/etc/hostname, $CLONE/etc/network/interfaces, etc
 # if I'm cloning into a card to be installed on another Pi.
 #
-echo -n "Hit Enter when ready to unmount the /dev/$DST_DISK partitions..."
-read resp
+#echo -n "Hit Enter when ready to unmount the /dev/$DST_DISK partitions..."
+#read resp
 
-echo "unmounting $CLONE/boot"
-umount $CLONE/boot
+#echo "unmounting $CLONE/boot"
+#umount $CLONE/boot
 
-echo "unmounting $CLONE"
-umount $CLONE
+#echo "unmounting $CLONE"
+#umount $CLONE
 
 
 echo "==============================="
